[eqRNC]
type = "design_variable"
summary = "eqRNC (design_variable)"
grid_base = "list"
grid_info = "0.8,1.0,1.2,1.5,2.0,3. "

[EqH2O]
type = "design_variable"
summary = "EqH2O (design_variable)"
grid_base = "list"
grid_info = "1 , 5 ,10, 50, 75"

[Sel]
type = "design_variable"
summary = "Sel (design_variable)"
grid_base = "list"
grid_info = "0.05, 0.1 , 0.25, 0.5"

[intensity]
type = "design_variable"
summary = "intensity (design_variable)"
grid_base = "list"
grid_info = "5, 10, 20, 30, 40"

[Concentration]
type = "design_variable"
summary = "Concentration (design_variable)"
grid_base = "list"
grid_info = "0.05, 0.1 , 0.25 ,0.5"

[faraday]
type = "design_variable"
summary = "faraday (design_variable)"
grid_base = "list"
grid_info = "2.,  2.5 ,3. , 3.5 ,4."
